# Generated by Django 6.0 on 2026-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Pin to top'),
        ),
    ]
